services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile.web
    depends_on:
      - db
    ports:
      - 5000:5000
    env_file:
      - .env.dev
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=code_executor_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ~/db_data/postgresql:/var/lib/postgresql/data
  db_admin:
    container_name: db_admin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 8080:80