services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./tmp:/tmp
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=code_executor_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ~/postgresql_data:/var/lib/postgresql/data
      # - C:/data/postgresql/data:/var/lib/postgresql/data
  db_admin:
    container_name: db_admin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 8080:80

networks:
  default:
    name: ce