services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=code_executor_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - C:/data/postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  db_admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 8080:80