package constants

const (
	ERROR_INVALID_REQUEST_BODY = "ERROR_INVALID_REQUEST_BODY"
	ERROR_INVALID_ACCESS_TOKEN = "ERROR_INVALID_ACCESS_TOKEN"
	ERROR_MISSING_JWT_CLAIMS   = "ERROR_MISSING_JWT_CLAIMS"
	ERROR_MKDIR                = "ERROR_MKDIR"
	ERROR_EXECUTION_ERROR      = "ERROR_EXECUTION_ERROR"

	ERROR_SNIPPET_CREATION = "ERROR_SNIPPET_CREATION"
	ERROR_SNIPPET_UPDATION = "ERROR_SNIPPET_UPDATION"
	ERROR_SNIPPET_DELETION = "ERROR_SNIPPET_DELETION"
	ERROR_SNIPPET_READ     = "ERROR_SNIPPET_READ"
)
