package constants

const (
	ERROR_INVALID_REQUEST_BODY = "ERROR_INVALID_REQUEST_BODY"
	ERROR_INVALID_ACCESS_TOKEN = "ERROR_INVALID_ACCESS_TOKEN"
	ERROR_MISSING_JWT_CLAIMS   = "ERROR_MISSING_JWT_CLAIMS"
)
