name: Build and Publish

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Delete old latest image
        uses: bots-house/ghcr-delete-image-action@v1.0.0
        with:
          owner: ${{ github.actor }}
          name: code_executor_golang
          token: ${{ secrets.GHCR_PAT }}
          tag: latest

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.prod
          tags: ghcr.io/rohandhamapurkar/code_executor_golang:latest
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
